# Generated by Django 3.2.9 on 2021-11-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_rename_tag_article_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='text',
            field=models.TextField(default='SomeText'),
            preserve_default=False,
        ),
    ]
