# Generated by Django 3.2.9 on 2021-11-04 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_scope_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='text',
        ),
    ]
